### ISSUE TITLE
Question about setup details

### ISSUE THREAD

**Issue by hyunW3** [ubc-vision/Prompting-Hard-Hardly-Prompting#2]
First, Thanks for the interesting work
I'm currently working on the environment setup, but I encountered several problems and question regarding it.

1. I tried to setup a conda environment with the provided environment.yaml with
`conda env create --file environment.yaml`
but it produces errors related to this repository 
`ERROR: [path]/Prompting-Hard-Hardly-Prompting does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found. ` 
it is due to installing current repository with editable mode https://github.com/ubc-vision/Prompting-Hard-Hardly-Prompting/blob/7b05889d60483bd46de1c20d65546610a9465f4b/environment.yaml#L31C5-L31C11
I guess it might be due to **missing updating 'setup.py' files on github repo.** 
2. related to [Navigating the Prompt Inversion](https://github.com/ubc-vision/Prompting-Hard-Hardly-Prompting#navigating-the-prompt-inversion) in READMD.md 
I have a question about 4th instruction related to "embedding_matrix.pt" contains the embeddings for the CLIP vocabulary (vocab.json).
**Where should I put "embedding_matrix.pt" ??**

Thank you for reading

**Comment by s-mahajan** [comment]
Hi, Thanks for you interest in our work! 
For 1. Follow the original LDM repository to set up the environment. 
2. You can place the embedding_matrix.pt at any location. You would need to update the path in https://github.com/ubc-vision/Prompting-Hard-Hardly-Prompting/blob/7b05889d60483bd46de1c20d65546610a9465f4b/ldm/modules/encoders/localclip_transformer.py#L260. 

Thanks!

**Comment by hyunW3** [comment]
Thank you!
