### ISSUE TITLE
Questions about training parameters

### ISSUE THREAD

**Issue by M-o-magic** [ubc-vision/Prompting-Hard-Hardly-Prompting#4]
"python main_textual_inversion.py"

Running this command will result in an error, so the command I am running is:

python main_textual_inversion.py -b ./configs/stable-diffusion/v1-inferrence.yaml --gpu 1

But it still reported an error: "Missing key data". 

So I want to know where to set the "image_path" parameter.

Sincerely looking forward to your reply .

**Comment by Zhazhan** [comment]
This works for me: 
python main_textual_inversion.py -b configs/latent-diffusion/inversion_config.yaml --gpus=0, -t True

**Comment by s-mahajan** [comment]
Hi, Hope the comment from Zhazhan helps. The config file is /latent-diffusion/inversion_config.yaml. Thanks!

**Comment by M-o-magic** [comment]
Thank you for your reply. I would like to know if this project supports generating a prompt from multiple images, or running on multiple GPUs?

**Comment by s-mahajan** [comment]
Hi, for generating a single prompt from multiple images (many to one), you can modify the data loader and pick an image randomly during optimization. For generating different prompts for each image, you can do different runs in parallel by specifying the image_path through a command line or a bash script.
